# Generated by Django 2.2.15 on 2020-08-03 21:15

from django.db import migrations, models
import django.db.models.deletion
import hotel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, max_length=512, null=True)),
                ('instructions', models.TextField(blank=True, max_length=2048, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=hotel.models.get_hotel_image_upload_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=hotel.models.get_hotel_image_upload_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=hotel.models.get_hotel_image_upload_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=hotel.models.get_hotel_image_upload_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=hotel.models.get_hotel_image_upload_path)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=hotel.models.get_hotel_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('has_breakfast', models.BooleanField(default=False)),
                ('adults_number', models.PositiveSmallIntegerField(default=0)),
                ('children_number', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
            ],
        ),
    ]
