# Generated by Django 2.2.15 on 2020-08-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20200803_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
    ]
