# Generated by Django 2.2.15 on 2020-08-04 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(choices=[('general', 'international'), ('customer_services', 'domestic'), ('public_spaces', 'public_spaces'), ('shopping', 'shopping'), ('transportation', 'transportatio'), ('sports', 'sports'), ('housekeeping', 'housekeeping'), ('hotel_services', 'hotel_services'), ('activities', 'activities'), ('misc', 'misc'), ('entertainment', 'entertainment'), ('foods_and_drinks', 'foods_and_drinks'), ('business_meetings', 'business_meetings')], max_length=64),
        ),
    ]
