# Generated by Django 2.2.15 on 2020-08-04 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20200804_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(choices=[('customer_services', 'customer_services'), ('public_spaces', 'public_spaces'), ('shopping', 'shopping'), ('transportation', 'transportatio'), ('sports', 'sports'), ('housekeeping', 'housekeeping'), ('hotel_services', 'hotel_services'), ('activities', 'activities'), ('misc', 'misc'), ('entertainment', 'entertainment'), ('foods_and_drinks', 'foods_and_drinks'), ('business_meetings', 'business_meetings')], max_length=64),
        ),
        migrations.CreateModel(
            name='Breadcrumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
            ],
        ),
    ]
