# Generated by Django 2.2.15 on 2020-08-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20200804_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='loc_x',
            field=models.DecimalField(decimal_places=16, default=-54.041680317979825, max_digits=18),
        ),
        migrations.AddField(
            model_name='hotel',
            name='loc_y',
            field=models.DecimalField(decimal_places=16, default=39.10622758640926, max_digits=18),
        ),
    ]
