# Generated by Django 2.2.15 on 2020-08-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20200804_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total',
            field=models.PositiveIntegerField(default=200000),
        ),
    ]
