# Generated by Django 2.2.15 on 2020-08-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_room_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=200000, null=True),
        ),
    ]
