# Generated by Django 2.2.15 on 2020-08-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20200807_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.PositiveIntegerField(default=1626321),
        ),
    ]
